# Generated by Django 4.0.5 on 2022-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.IntegerField(verbose_name='Количество стадий')),
                ('components', models.IntegerField(verbose_name='Количество компонентов')),
                ('experients', models.IntegerField(verbose_name='Количество опытов')),
            ],
            options={
                'verbose_name': 'Матрицы',
                'verbose_name_plural': 'Матрицы',
            },
        ),
    ]
